name: CI
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Prepare
        run: yarn global add lint-md-cli remark-cli remark-preset-lint-recommended fnlint

      - name: Checkout
        uses: actions/checkout@v2

      - name: Get Diff Action
        uses: technote-space/get-diff-action@v4.0.1
        with:
          PATTERNS: |
            source/**/*.md
            *.md

      - name: Lint
        if: env.GIT_DIFF
        run: |
          remark -f ${{ env.GIT_DIFF }}
          lint-md ${{ env.GIT_DIFF }}
          fnlint -c .fnlint.json
